- name:  Extend inventory with hypervisor hosts
  hosts: localhost
  vars_files:
    - variables.yaml
    - vault-variables.yaml
    - bm-ansible-nodes.json
  tasks:
  - name: Add all hypervisor group-host
    ansible.builtin.add_host:
      name: "{{ item.hypervisor_name }}"
      ansible_ssh_user: "{{ item.hypervisor_user }}"
      ansible_ssh_private_key_file: "{{ item.hypervisor_ssh_key }}"
      groups:
        - hypervisor_host
    with_items: "{{ master_nodes }}"
    when: item.hypervisor_name != "localhost"

- name:  Build master hosts
  hosts:
    - localhost
    - hypervisor_host
  vars_files:
    - variables.yaml
    - vault-variables.yaml
    - bm-ansible-nodes.json
  tasks:

  - name: Create Image for each master
    shell: |
      qemu-img create -f qcow2 -o preallocation=metadata {{ item.hypervisor_image_dir }}/{{ item.name }}.qcow2 {{ master.disk }}
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ master_nodes }}"

  - name: Define master VMs - virtualbmc
    community.libvirt.virt_install:
      state: present
      import: true
      name: "{{ item.name }}"
      memory: "{{ master.memory }}"
      vcpus: "{{ master.cpu }}"
      cpu:
        model: "host-passthrough"
      osinfo:
        name: "rhel9.5"
      disks:
        - path: "{{ item.hypervisor_image_dir }}/{{ item.name }}.qcow2"
          bus: "virtio"
          format: "qcow2"
      networks:
        - bridge: "{{ bridge_prov }}"
          model:
            type: virtio
          mac:
            address: "{{ item.provisioning_mac }}"
        - bridge: "{{ bridge_bm }}"
          model:
            type: virtio
          mac:
            address: "{{ item.baremetal_mac }}"
      graphics:
        type: vnc
        listen: "0.0.0.0"
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ master_nodes }}"
    when:
      - not redfish.enable|bool

  - name: Define master VMs - redfish
    community.libvirt.virt_install:
      state: present
      import: true
      name: "{{ item.name }}"
      memory: "{{ master.memory }}"
      vcpus: "{{ master.cpu }}"
      cpu:
        model: "host-passthrough"
      osinfo:
        name: "rhel9.5"
      disks:
        - path: "{{ item.hypervisor_image_dir }}/{{ item.name }}.qcow2"
          bus: "virtio"
          format: "qcow2"
      networks:
        - bridge: "{{ bridge_bm }}"
          model:
            type: virtio
          mac:
            address: "{{ item.baremetal_mac }}"
      graphics:
        type: vnc
        listen: "0.0.0.0"
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ master_nodes }}"
    when:
      - redfish.enable|bool
  
  # TODO: check ip address available in the hypervisor
  - name: Create virtualbmc interface
    shell: |
      vbmc add "{{ item.name }}" --address "{{ item.vbmc_ip }}" --port "{{ item.vbmc_port }}" --username admin --password "{{ secure_password }}"
      vbmc start "{{ item.name }}"
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ master_nodes }}"
    when:
      - not redfish.enable|bool

